name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    strategy:
      matrix:
        ros_distro: [foxy]
    runs-on: ubuntu-20.04
    container: ros:${{ matrix.ros_distro }}-ros-core
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/action-ros-ci@v0.2
      container: ros:${{ matrix.ros_distro }}-ros-core
      with:
        target-ros2-distro: ${{ matrix.ros_distro }}
        import-token: ${{ secrets.CI_TOKEN }}
        package-name: pcl_utils

